# Generated by Django 4.2 on 2023-05-08 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=355)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "telephone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in the format '+32 XX XXX XX XX'",
                                regex="^\\+32\\s\\d{2}\\s\\d{3}\\s\\d{2}\\s\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("adress_start", models.CharField(max_length=300)),
                ("stage_start", models.CharField(max_length=110)),
                ("adress_arrived", models.CharField(blank=True, max_length=300)),
                ("stage_arrived", models.CharField(blank=True, max_length=110)),
                ("message", models.TextField(max_length=1500)),
            ],
        ),
    ]
