# Generated by Django 4.2 on 2023-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applift", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Keyword",
            new_name="Keywords",
        ),
    ]
